version: "3.7"

volumes:

services:
	mariadb:
		image: mariadb
		restart: always
		build: ./requirements/mariadb/
		user: root
		
		ports:
			- "3306:3306"
	NGINX:
		build: ./requirements/nginx
		command:
		ports:
			- "443:443"
	WordPress+PHP:
		build:
		command:
		depends_on:
			- mariadb
network_mode: host
