version: "3.7"
volumes:
 wordpress:
  name: wordpress
  driver: local
  driver_opts:
   o: bind
   type: none
   device: /home/nagrivan/data/wordpress
 database:
  name: database
  driver: local
  driver_opts:
   o: bind
   type: none
   device: /home/nagrivan/data/database
services:
 mariadb:
  image: mariadb
  volumes:
   - database:/var/www/html
  restart: always
  env_file: .env
  build: ./requirements/mariadb/
  networks:
   - all_services
  user: root
  ports:
   - "3306:3306"
 NGINX:
  depends_on:
    - WordPress_PHP
  image: nginx
  volumes:
   - wordpress:/var/www/html
  restart: always
  env_file: .env
  build: ./requirements/nginx
  networks:
   - all_services
  user: root
  ports:
   - "443:443"
 WordPress_PHP:
  depends_on:
    - mariadb
  image: wordpress
  volumes:
   - wordpress:/var/www/html
  restart: always
  env_file: .env
  build: ./requirements/wordpress
  networks:
   - all_services
  user: root
  ports:
   - "9000:9000"
networks:
 all_services:
  name: all_services
  driver: bridge
