version: "3.9"
services:
	mariadb:
		build: ./requirements/mariadb/
		command:
		ports:
			- 3306:3306
	NGINX:
		build: ./requirements/nginx
		command:
		ports:
			- 9000:9000
	WordPress+PHP:
		build:
		command:
		depends_on:
			- mariadb
network_mode: host
